# .circleci/config.yml file
version: 2.2

jobs:
  build:            # job name
    docker:         # executor type
      - image: cimg/base:current # Docker image that installs Docker and has Git,
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker:
          version: edge
      - run:
          name: reverseproxy
          command: |
            echo "Inside the Build and push Docker image step "
            docker --version # print the version for logging
            ls
            cd udagram-reverseproxy
            docker build -t "$DOCKER_USERNAME"/reverseproxy .        
            docker tag "$DOCKER_USERNAME"/reverseproxy "$DOCKER_USERNAME"/reverseproxy:v1
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push "$DOCKER_USERNAME"/reverseproxy:v1
      - run:
          name: udagram-api-user
          command: |
            echo "Inside the Build and push Docker image step "
            docker --version # print the version for logging
            cd udagram-api-user
            docker build -t "$DOCKER_USERNAME"/udagram-api-user .        
            docker tag "$DOCKER_USERNAME"/udagram-api-user "$DOCKER_USERNAME"/udagram-api-user:v1
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push "$DOCKER_USERNAME"/udagram-api-user:v1
      - run:
          name: udagram-api-feed
          command: |
            echo "Inside the Build and push Docker image step "
            docker --version # print the version for logging
            cd udagram-api-feed
            docker build -t "$DOCKER_USERNAME"/udagram-api-feed .        
            docker tag "$DOCKER_USERNAME"/udagram-api-feed "$DOCKER_USERNAME"/udagram-api-feed:v1
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push "$DOCKER_USERNAME"/udagram-api-feed:v1
      - run:
          name: udagram-frontend
          command: |
            echo "Inside the Build and push Docker image step "
            docker --version # print the version for logging
            cd udagram-frontend
            docker build -t "$DOCKER_USERNAME"/udagram-frontend .        
            docker tag "$DOCKER_USERNAME"/udagram-frontend "$DOCKER_USERNAME"/udagram-frontend:v1
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push "$DOCKER_USERNAME"/udagram-frontend:v1